import {researchText} from './research-details.mjs?v=20260921-szu-rating';
import {portfolioProjects} from './portfolio-data.mjs?v=20260921-szu-rating';
import {authorsMarkup,creditWords} from './research-authors.mjs?v=20260921-szu-rating';
const portfolioUrl='https://www.dropbox.com/scl/fi/mka6zodudayeshsd66xnn/Lei-Shuyu-s-Portfolio.pdf?rlkey=9b5he2gn2nomp72278k6gu6uc&dl=1';
const projects=[
 {id:'walking',title:'Whose 15-minute city?',topic:'Age-friendly accessibility',year:'2026',place:'Hong Kong',image:'walking.webp',alt:'Research map showing spatial clusters of older residents and walking accessibility in Hong Kong',venue:'Journal of Transport Geography',doi:'10.1016/j.jtrangeo.2026.104656',deck:'Rethinking proximity through the walking needs of older adults.',body:'A single walking-time threshold can hide important differences between age groups. This research develops an age-sensitive X-minute-city framework using travel survey records, facility locations, and a three-dimensional pedestrian network.',finding:'Older adults complete most daily walking trips within 5–12 minutes, depending on age and destination. Mapping these differences helps locate neighbourhoods where conventional proximity measures may overstate accessibility.',methods:'Travel survey analysis; age-specific walking thresholds; GIS network analysis; spatial clustering.',authors:'Shuyu Lei, Mushu Zhao, Jiangping Zhou, Xiaochun Yang',caption:'Spatial clustering of older-adult population and accessibility. Figure 13, Lei et al. (2026), Journal of Transport Geography.'},
 {id:'heat',title:'When heat changes the journey',topic:'Heat and unequal mobility impacts',year:'2026',place:'New York City',image:'heat.webp',alt:'New York City subway network and research area map from the extreme heat study',venue:'npj Sustainable Mobility and Transport',doi:'10.1038/s44333-026-00083-7',deck:'Who changes their subway travel when the city gets hotter?',body:'Extreme heat does not affect every transit passenger in the same way. This collaborative study examines differences in New York City subway ridership during extreme heat events, with attention to older adults and passengers with disabilities.',finding:'The study finds larger ridership declines among seniors and passengers with disabilities, particularly on weekends. These patterns highlight the importance of considering passengers with different mobility needs in climate-responsive transport planning.',methods:'Subway ridership analysis; extreme heat events; comparison across passenger groups.',authors:'Mushu Zhao, Shuyu Lei, Songyang Li, Weifeng Li',caption:'New York City research area. Figure 1, Zhao et al. (2026), npj Sustainable Mobility and Transport.'},
 {id:'poverty',title:'The geography of opportunity',topic:'Spatial networks & poverty',year:'2025',place:'Nairobi',image:'poverty.webp',alt:'Map of multidimensional poverty across Nairobi from the Applied Geography study',venue:'Applied Geography',doi:'10.1016/j.apgeog.2025.103578',deck:'Connecting neighbourhood networks with multidimensional poverty.',body:'What can the structure of a street network tell us about disadvantage? This collaborative study links geocoded household survey data in Nairobi with 16 spatial network indicators, comparing theory-driven and data-driven approaches.',finding:'Network density and efficiency are associated with lower multidimensional poverty, while severance is associated with greater risk. These are associations, offering evidence for further investigation of neighbourhood connectivity and living conditions.',methods:'Geocoded household survey analysis; street-network indicators; logistic regression; XGBoost.',authors:'James Gachanja, Shuyu Lei, Nashon Adero',caption:'Spatial distribution of multidimensional poverty in Nairobi. Figure 3, Gachanja, Lei & Adero (2025), Applied Geography.'},
 {id:'transit',title:'Mind the travel-time gap',topic:'Inclusive public transport',year:'2026',place:'Hong Kong',image:'transit.webp',alt:'Eight Hong Kong origin-destination maps showing age-related travel-time differences',venue:'Transportation Research Part A: Policy and Practice',doi:'10.1016/j.tra.2025.104842',deck:'Using smart-card data to reveal how older people experience the metro.',body:'Stations that work well for one group may be more difficult for another. This research uses travel-time differences between older and younger passengers to evaluate age-friendliness at station and station-pair levels, after controlling for confounding effects.',finding:'The framework identifies locations where older passengers experience greater travel-time penalties. Findings support station-level considerations such as staff assistance, clear wayfinding and accessible routes.',methods:'Smart-card data processing; clustering; statistical modelling; confounder control; spatial analysis.',authors:'Shuyu Lei, Mingzhi Zhou, Weipeng Deng, Yihong Tang, Jiangping Zhou',caption:'Origin-destination pairs with significant travel-time differences. Figure 7, Lei et al. (2026), Transportation Research Part A: Policy and Practice.'},
 {id:'thermal',title:'A cooler way to reach transit',topic:'Climate-responsive urban design',year:'2026',place:'Shanghai',image:'thermal.webp',alt:'Street-view imagery and semantic segmentation of buildings, vegetation, and road space',venue:'Sustainable Cities and Society',doi:'10.1016/j.scs.2026.107254',deck:'Bringing thermal comfort into transit-oriented development.',body:'This collaborative study evaluates outdoor thermal comfort in Shanghai during summer and examines nonlinear, spatially heterogeneous relationships between transit-oriented development and heat exposure.',finding:'Metro catchments with greater variation in building height and higher vegetation ratios are associated with better thermal comfort; population and building density are associated with greater discomfort.',methods:'Street-view imagery; semantic segmentation; built-environment analysis; GeoXAI.',authors:'Mushu Zhao, Shuyu Lei, Weifeng Li',caption:'Street-view imagery and semantic segmentation. Figure 2, Zhao, Lei & Li (2026), Sustainable Cities and Society.'},
 {id:'city-connect',title:'City Connect 15+',topic:'Applied GIS & urban accessibility',year:'2023',place:'Hong Kong',image:'city-connect.webp',alt:'City Connect 15+ project overview, an accessibility prototype for Hong Kong',venue:'Merit Award · Common Spatial Data Infrastructure (CSDI) Awards',deck:'An age-sensitive approach to everyday destinations.',body:'City Connect 15+ is a collaborative accessibility prototype for exploring a 15-minute city in Hong Kong. The project brings together a three-dimensional pedestrian network, facility accessibility, barrier-free considerations, and weather scenarios.',finding:'The prototype received a Merit Award in the Open Category of the 2023 Hong Kong CSDI Awards. My contribution connected spatial research, mapping, and visual communication.',methods:'GIS accessibility modelling; 2SFCA; 3D pedestrian networks; data visualisation.',authors:'ESG Connector team: Cheng Chi Chiu, Zhang Jin, Shuyu Lei, Weipeng Deng',caption:'Project material from City Connect 15+, ESG Connector team (2023).'},
 {id:'smart-community',title:'Smart Community',topic:'Urban design',year:'Student work',place:'Shenzhen',image:'smart-community.webp',alt:'Axonometric urban design proposal with buildings, green spaces, and pedestrian connections',deck:'An urban design exploration of community, movement, and shared space.',body:'Selected work from my urban design portfolio explores the relationship between built form, public space, and everyday life. The drawings combine spatial analysis, master planning, and architectural visualisation.',methods:'Urban design; master planning; spatial diagrams; architectural visualisation.',caption:'Smart Community. Student design work from Shuyu Lei’s portfolio.',url:portfolioUrl},
 {id:'milan',title:'The Loop',topic:'Landscape & urban connections',year:'2018',place:'Milan',image:'milan.webp',alt:'Landscape and pedestrian network design plan from a student project in Milan',deck:'Landscape as a framework for urban connections.',body:'Developed during my academic exchange at Politecnico di Milano, this student project examines landscape and urban connections in the Milan region. It reflects an interest in how routes, green space, and urban form can be considered together.',methods:'Landscape planning; urban analysis; mapping; design communication.',caption:'The Loop. Student design work from Shuyu Lei’s portfolio.',url:portfolioUrl},
 {id:'landscape',title:'Multivariate Space',topic:'Landscape design',year:'Student work',place:'Shenzhen',image:'landscape.webp',alt:'Landscape proposal for an architecture and urban planning school with planted terraces and public space',deck:'Reimagining a campus landscape through shared outdoor space.',body:'A landscape renovation proposal for a school of architecture and urban planning. The portfolio combines site analysis, planting, circulation, and visualisation to explore the relationship between the learning environment and outdoor life.',methods:'Landscape design; site analysis; planting strategy; visualisation.',caption:'Multivariate Space. Student design work from Shuyu Lei’s portfolio.',url:portfolioUrl}
];
const escapeHtml=(s)=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=(name)=>`<i data-lucide="${name}" aria-hidden="true"></i>`;
function projectCard(p){
 const visual=`<div class="project-visual"><img src="assets/${p.image}" alt="${escapeHtml(p.alt)}" width="600" height="400" ${p.id==='walking'?'fetchpriority="high"':'loading="lazy"'}></div>`;
 const meta=`${p.roleLabel?`<p class="authorship authorship-${p.authorship}">${escapeHtml(p.roleLabel)}</p>`:''}<div class="project-label"><span>${escapeHtml(p.topic)}</span><span>${escapeHtml(p.year)} · ${escapeHtml(p.place)}</span></div>`;
 if(p.page)return `<a class="project-card" href="${escapeHtml(p.page)}" data-design="${p.id}">${visual}${meta}<h3>${escapeHtml(p.title)} ${icon('arrow-up-right')}</h3><p>${escapeHtml(p.deck)}</p>${p.venue?`<div class="project-venue">${escapeHtml(p.venue)}</div>`:''}</a>`;
 const w=creditWords[p.uiLang]||creditWords.en;
 const href=`index.html?project=${encodeURIComponent(p.id)}`;
 const attrs=`href="${href}" data-project="${p.id}"`;
 return `<article class="project-card" data-project="${p.id}"><a ${attrs} aria-label="${escapeHtml(p.title)}">${visual}</a>${meta}<h3><a ${attrs} aria-label="${escapeHtml(p.title)} · ${w.details}"><span>${escapeHtml(p.title)}</span><span class="detail-arrow" title="${w.details}">${icon('arrow-up-right')}<span class="detail-tooltip" aria-hidden="true">${w.details}</span></span></a></h3><p class="project-summary">${escapeHtml(p.deck)}</p><div class="project-source" aria-label="${p.doi?w.journal:w.award}"><div class="project-venue">${escapeHtml(p.venue||'')}</div></div>${['heat','thermal','poverty'].includes(p.id)?authorsMarkup(p,{compact:true}):''}</article>`;
}

const updates={
 poverty:{image:'poverty-network-shape-hd.webp',galleryImage:'poverty-metrics-hd.webp',alt:'Map of street-network shape and efficiency across Nairobi neighbourhoods',caption:'Spatial network metrics across Nairobi neighbourhoods. Figure 4, Gachanja, Lei & Adero (2025), Applied Geography.'},
 thermal:{image:'thermal-comparison-borderless.webp',galleryImage:'thermal-comparison.webp',alt:'Shanghai thermal comfort maps comparing average and 90th-percentile conditions',caption:'Relative thermal comfort in Shanghai: (a) average and (b) 90th-percentile MTHI. Figure 7, Zhao, Lei & Li (2026), Sustainable Cities and Society.'},
 walking:{image:'walking-routes-cover.webp',galleryImage:'walking-concept-full.webp',alt:'Four age-specific walking route scenarios on Hong Kong’s three-dimensional pedestrian network',caption:'Integrated conceptual and analytical framework. Figure 1, Lei et al. (2026), Journal of Transport Geography.'},
 transit:{image:'transit-weekday-daily-cover.webp',galleryImage:'transit-od-original.webp',alt:'Map of Hong Kong metro journeys with age-related travel-time disparities on weekdays',caption:'Top 50 origin-destination pairs with significant age-related travel-time differences across eight temporal scenarios. Figure 7, Lei et al. (2026), Transportation Research Part A: Policy and Practice.'},
 heat:{image:'heat-scatter.webp',galleryImage:'heat-scatter.webp',alt:'Heat index and subway ridership scatterplots for Fair Fares and senior or disability fare groups',caption:'Heat index and ridership during warm seasons, 2022–2024: Fair Fares and seniors / people with disabilities fare groups. Figure 5, Zhao et al. (2026), npj Sustainable Mobility and Transport.'},
 'city-connect':{image:'city-connect-cover.webp',alt:'Zoomed-in City Connect 15+ route-search map showing walking pace, weather and nearby amenities',galleryImage:'city-connect-platform-team.webp',caption:'City Connect 15+: the original web and mobile platform overview and ESG Connector team. Final presentation (2023), slide 2.',url:'https://csdigeolab.gov.hk/en/event-highlight/csdi-awards-2023-eh',linkKey:'award',links:[{url:'https://gradsch.hku.hk/news_and_events/newsletter/awards-and-achievements-0',key:'hkuAward'},{url:'https://csdigeolab.gov.hk/images/CSDI_Awards_2023/Cat_4_Work_Brief/City_Connect_15_-_Short_Brief.pdf',key:'projectBrief'}]}
};
projects.forEach(p=>Object.assign(p,updates[p.id]||{}));
projects.push({id:'kowloon',title:'An age-friendly Kowloon City',topic:'Community planning studio',year:'2020\u20132021',place:'Hong Kong',image:'kowloon-plan.webp',alt:'Age-friendly community plan for Kowloon City',deck:'Community engagement, accessible streets and ageing in place.',body:'Planning for an Age Friendly Kowloon City was developed in HKU\u2019s Community Planning Studio (URBP8001). The team combined surveys, stakeholder interviews and a community workshop to develop an age-friendly community plan.',finding:'As a team member, I contributed to the final presentation drawings and designed the workshop\u2019s promotional board. The team report proposes twelve interventions spanning connected routes, inclusive environments, intergenerational spaces and wellbeing.',methods:'Community engagement; surveys and interviews; spatial planning; design drawings; visual communication.',authors:'Cheng Chi Chiu David; Chu Wing Sing Don; Lee Ming Wai Vivian; Lei Shuyu Leslie; Tam Tsz Ho Cyrus; Tse Yi Lam Gloria; Wong Yui Hin Isaac; Ying Pui Yan Anson',caption:'Final Age Friendly Community Plan, Figure 5.3.3, report page 55. Team project, HKU Community Planning Studio.',url:'https://foa-media.arch.hku.hk/media/upload/2021/02/URBP8001_Final-report_Group-2-IC-Planning-Consultant.pdf',linkKey:'report',links:[{url:'https://www.arch.hku.hk/gallery/upad/community-planning-workshop-2021/',key:'studioPage'}]});
for(const item of portfolioProjects){const existing=projects.find(p=>p.id===item.id);if(existing)Object.assign(existing,item);else projects.push(item);}
Object.assign(projects.find(p=>p.id==='kowloon'),{page:'project-kowloon.html',role:'Team member; final presentation drawings and workshop promotional board.',pages:[]});
const researchIds=['walking','transit','city-connect','heat','thermal','poverty'];
const designIds=['kowloon',...portfolioProjects.map(p=>p.id).filter(id=>!['experimental','residential'].includes(id))];
projects.forEach(p=>Object.assign(p,researchText(p)));
const orderedProjects=ids=>ids.map(id=>projects.find(p=>p.id===id));
export {projects,researchIds,designIds,orderedProjects,escapeHtml,icon,projectCard};
